Add support for `dc:creator`
jpmonette/feed pull request #131
Opened 2020-10-18 09:53 UTC by deadcoder0904

Closes #130

2021-01-22 02:43 UTC, chazmcgarvey requested changes
How about something like this?

- Adds the schema for dc, if creator is used.
- Allow multiple creators.
- Do author or creator, not both (as one [best practice suggests](https://www.rssboard.org/rss-profile#namespace-elements-dublin-creator)).

2021-01-22 02:43 UTC, chazmcgarvey commented on src/rss2.ts
>          }
```suggestion
      item["dc:creator"] = [];
      entry.author.map((author: Author) => {
        if (author.email && author.name) {
          item.author.push({ _text: author.email + " (" + author.name + ")" });
        } else if (author.name) {
          isDublinCore = true;
          item["dc:creator"].push({ _cdata: author.name });
        }
```

And up above:
```
  let isDublinCore = false;
```

And down below:

```
  if (isDublinCore) {
    base.rss._attributes["xmlns:dc"] = "http://purl.org/dc/elements/1.1/";
  }
```

2021-02-17 16:37 UTC, paul-uz commented
This should not be added to the RSS2 spec, as by definition, it is not in the RSS2 spec (https://validator.w3.org/feed/docs/rss2.html)

2021-02-17 16:58 UTC, chazmcgarvey commented
> This should not be added to the RSS2 spec, as by definition, it is not in the RSS2 spec (https://validator.w3.org/feed/docs/rss2.html)

Are you referring to the spec file modified by this pull request? That's a test file. "spec" in the filename does not mean it has anything to do with the RSS2 spec, it's just a Jest convention.

If you're saying this node module shouldn't use extra namespaces, consider this from the document you link:

> **RSS is by no means a perfect format**, but it is very popular and widely supported. Having a settled spec is something RSS has needed for a long time. The purpose of this work is to help it become a unchanging thing, to foster growth in the market that is developing around it, and to clear the path for innovation in new syndication formats. Therefore, the RSS spec is, for all practical purposes, frozen at version 2.0.1. We anticipate possible 2.0.2 or 2.0.3 versions, etc. only for the purpose of clarifying the specification, not for adding new features to the format. **Subsequent work should happen in modules, using namespaces**, and in completely new syndication formats, with new names.

(Emphasis mine.)

Nobody is saying that the Dublin core namespace is part of the RSS2 spec. The RSS2 spec over time has proven to be have problems and is incomplete, which is why new namespaces -- which have schemas apart from the RSS2 schema -- have added missing functionality. Dublin core is such a namespace. It is popular and well-supported by readers.

2025-05-06 15:56 UTC, closed without merging